version: '3.1'

services:

  db:
    container_name: mysql-8.0-bookworm
    image: mysql:8.0-bookworm
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Samira1966.
    ports:
      - 3306:3306

  adminer:
    container_name: adminer-4.8.0-standalone
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 8080:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '9081:80'
      - '9025:25'
      - '143:143'
